### ISSUE TITLE
Cursor not found on server

### ISSUE THREAD

**Issue by sowe** [pentaho/pentaho-mongodb-plugin#29]
Hi i've this error?
num of collection is a 47110.
driver mongodb is a 2.7.2
PDI: 4.4.0 Stable
/************************************* ERROR*********************/
ERROR 26-07 11:13:23,407 - Data - Unexpected error
ERROR 26-07 11:13:23,408 - Data - com.mongodb.MongoException$CursorNotFound: cursor not found on server
	at com.mongodb.DBApiLayer$Result.init(DBApiLayer.java:391)
	at com.mongodb.DBApiLayer$Result._advance(DBApiLayer.java:454)
	at com.mongodb.DBApiLayer$Result.hasNext(DBApiLayer.java:418)
	at com.mongodb.DBCursor._hasNext(DBCursor.java:503)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:523)
	at org.pentaho.di.trans.steps.mongodbinput.MongoDbInput.processRow(MongoDbInput.java:77)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:50)
	at java.lang.Thread.run(Thread.java:662)

**Comment by morishoji** [comment]
I think this issue might be fixed by the addition of the following.
`data.cursor.addOption(QUERYOPTION_NOTIMEOUT)`
Some cursor options should be controlled from the GUI.

http://dba.stackexchange.com/questions/69517/mongodb-shard-disable-cursor-timeout

**Comment by pamval** [comment]
Hello. We use jira.pentaho.com as our issue tracking system. Could you open an issue there regarding this behavior ? Thanks!

**Comment by pamval** [comment]
Actually, I think this was already reported in http://jira.pentaho.com/browse/PDI-10324
